AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SSMDocumentName:
    Type: String
  EventBridgeRoleArn:
    Type: String
  AutoScalingGroupName:
    Type: String

Resources: 
  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: eventbridge-dlq

  DLQPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DLQ
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt DLQ.Arn

  Myeventbridgerule:
    Type: AWS::Events::Rule
    Properties:
      Description: Events Rule with EcsParameters
      EventPattern:
        source:
          - aws.autoscaling
        detail-type:
          - EC2 Instance-terminate Lifecycle Action
        detail:
          AutoScalingGroupName:
            - !Ref AutoScalingGroupName
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:document/${SSMDocumentName}"
          Id: TargetSSMAutomation
          RoleArn: !Ref EventBridgeRoleArn

          # InputTransformer:
          #   InputPathsMap:
          #     instanceId: $.detail.EC2InstanceId
          #     asgName: $.detail.AutoScalingGroupName
          #     lifecycleHookName: $.detail.LifecycleHookName

          #   InputTemplate: !Sub |
          #     {
          #       "DocumentName": "${SSMDocumentName}",
          #       "Parameters": {
          #         "InstanceId": ["<instanceId>"],
          #         "ASGName": ["<asgName>"],
          #         "LifecycleHookName": ["<lifecycleHookName>"],
          #         "AutomationAssumeRole": ["arn:aws:iam::${AWS::AccountId}:role/SSMAutomationRole"]
          #       }
          #     }
          Input: !Sub |
            {
              "DocumentName": "${SSMDocumentName}",
              "Parameters": {
                "InstanceId": ["i-1234567890abcdef0"],
                "ASGName": ["Q1-asg"],
                "LifecycleHookName": ["test-hook"],
                "AutomationAssumeRole": ["arn:aws:iam::${AWS::AccountId}:role/SSMAutomationRole"]
              }
            }

          DeadLetterConfig:
            Arn: !GetAtt DLQ.Arn